### ISSUE TITLE
panic in main branch

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1383]
After syncing with main and doing `make clean` (to build with latest libbpf) then `make` (both from tracee-ebpf dir) I get the following panic:

```
[yaniv@yaniv-aqua tracee-ebpf]$ sudo ./dist/tracee-ebpf
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7ffe32b239e0 pc=0x7ffe32b239e0]

runtime stack:
runtime.throw({0x795490, 0x456747})
	/usr/lib/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:719 +0x396

goroutine 50 [syscall]:
runtime.cgocall(0x6b4d80, 0xc0008d0f18)
	/usr/lib/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0008d0ef0 sp=0xc0008d0eb8 pc=0x40de1c
github.com/aquasecurity/libbpfgo._Cfunc_perf_buffer__poll(0x29c2090, 0x12c)
	_cgo_gotypes.go:890 +0x4c fp=0xc0008d0f18 sp=0xc0008d0ef0 pc=0x54a48c
github.com/aquasecurity/libbpfgo.(*PerfBuffer).poll.func1(0x0)
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1283 +0x4e fp=0xc0008d0f50 sp=0xc0008d0f18 pc=0x551eae
github.com/aquasecurity/libbpfgo.(*PerfBuffer).poll(0xc000a040c0)
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1283 +0x85 fp=0xc0008d0fc8 sp=0xc0008d0f50 pc=0x551d85
github.com/aquasecurity/libbpfgo.(*PerfBuffer).Start·dwrap·3()
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1229 +0x26 fp=0xc0008d0fe0 sp=0xc0008d0fc8 pc=0x551a06
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0008d0fe8 sp=0xc0008d0fe0 pc=0x46cea1
created by github.com/aquasecurity/libbpfgo.(*PerfBuffer).Start
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1229 +0x9b

goroutine 1 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run(0xc000334000)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/tracee.go:946 +0x271
main.main.func1(0xc00026c7c0)
	/home/yaniv/src/tracee/cmd/tracee-ebpf/main.go:205 +0x125c
github.com/urfave/cli/v2.(*App).RunContext(0xc00010b860, {0xbea6b8, 0xc000016100}, {0xc000012200, 0x1, 0x1})
	/home/yaniv/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x7a8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/yaniv/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/yaniv/src/tracee/cmd/tracee-ebpf/main.go:263 +0x75c

goroutine 20 [select]:
main.main.func1.1()
	/home/yaniv/src/tracee/cmd/tracee-ebpf/main.go:194 +0x12d
created by main.main.func1
	/home/yaniv/src/tracee/cmd/tracee-ebpf/main.go:191 +0x124f

goroutine 8 [syscall]:
os/signal.signal_recv()
	/usr/lib/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/usr/lib/go/src/os/signal/signal.go:151 +0x2c

goroutine 51 [syscall]:
github.com/aquasecurity/libbpfgo._Cfunc_perf_buffer__poll(0x29d36e0, 0x12c)
	_cgo_gotypes.go:890 +0x4c
github.com/aquasecurity/libbpfgo.(*PerfBuffer).poll.func1(0x0)
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1283 +0x4e
github.com/aquasecurity/libbpfgo.(*PerfBuffer).poll(0xc000a04100)
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1283 +0x85
created by github.com/aquasecurity/libbpfgo.(*PerfBuffer).Start
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1229 +0x9b

goroutine 52 [syscall]:
github.com/aquasecurity/libbpfgo._Cfunc_perf_buffer__poll(0x29d6ef0, 0x12c)
	_cgo_gotypes.go:890 +0x4c
github.com/aquasecurity/libbpfgo.(*PerfBuffer).poll.func1(0x0)
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1283 +0x4e
github.com/aquasecurity/libbpfgo.(*PerfBuffer).poll(0xc000a04140)
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1283 +0x85
created by github.com/aquasecurity/libbpfgo.(*PerfBuffer).Start
	/home/yaniv/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.2.4-libbpf-0.6.1/libbpfgo.go:1229 +0x9b

goroutine 53 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).processLostEvents(0xc000334000)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_processor.go:17 +0x36
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run
	/home/yaniv/src/tracee/tracee-ebpf/tracee/tracee.go:942 +0x14f

goroutine 54 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).WaitForPipeline(0xc000334000, {0xc000dfa020, 0xc000072120, 0x0})
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:225 +0xac
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).handleEvents(0x0, 0x0)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:56 +0x110
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run
	/home/yaniv/src/tracee/tracee-ebpf/tracee/tracee.go:943 +0x1cf

goroutine 55 [select]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).processFileWrites(0xc000334000)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/write_capture.go:62 +0xca
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run
	/home/yaniv/src/tracee/tracee-ebpf/tracee/tracee.go:944 +0x217

goroutine 56 [select]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).processNetEvents(0xc000334000)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/net_events.go:17 +0xc5
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).Run
	/home/yaniv/src/tracee/tracee-ebpf/tracee/tracee.go:945 +0x265

goroutine 38 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).decodeEvents.func1()
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:66 +0x105
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).decodeEvents
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:63 +0xd2

goroutine 39 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).processEvents.func1()
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:151 +0xab
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.(*Tracee).processEvents
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:149 +0xc5

goroutine 40 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.MergeErrors.func1(0x0)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:243 +0x74
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.MergeErrors
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:250 +0xb9

goroutine 41 [chan receive]:
github.com/aquasecurity/tracee/tracee-ebpf/tracee.MergeErrors.func1(0x0)
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:243 +0x74
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.MergeErrors
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:250 +0xb9

goroutine 42 [semacquire]:
sync.runtime_Semacquire(0x0)
	/usr/lib/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x0)
	/usr/lib/go/src/sync/waitgroup.go:130 +0x71
github.com/aquasecurity/tracee/tracee-ebpf/tracee.MergeErrors.func2()
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:256 +0x26
created by github.com/aquasecurity/tracee/tracee-ebpf/tracee.MergeErrors
	/home/yaniv/src/tracee/tracee-ebpf/tracee/events_pipeline.go:255 +0x192
```

**Comment by yanivagman** [comment]
Seems to be related to libbpf.
When I use libbpf 0.5.0 with main - works
With libbpf 0.6.1 (which we currently use for our libbpf submodule) - fails

**Comment by yanivagman** [comment]
Bisecting:

```
011a01594c52ace549cb153900ab8c7980572583 is the first bad commit
commit 011a01594c52ace549cb153900ab8c7980572583
Author: Andrii Nakryiko <andrii@kernel.org>
Date:   Wed Nov 10 21:36:20 2021 -0800

    libbpf: Make perf_buffer__new() use OPTS-based interface
    
    Add new variants of perf_buffer__new() and perf_buffer__new_raw() that
    use OPTS-based options for future extensibility ([0]). Given all the
    currently used API names are best fits, re-use them and use
    ___libbpf_override() approach and symbol versioning to preserve ABI and
    source code compatibility. struct perf_buffer_opts and struct
    perf_buffer_raw_opts are kept as well, but they are restructured such
    that they are OPTS-based when used with new APIs. For struct
    perf_buffer_raw_opts we keep few fields intact, so we have to also
    preserve the memory location of them both when used as OPTS and for
    legacy API variants. This is achieved with anonymous padding for OPTS
    "incarnation" of the struct.  These pads can be eventually used for new
    options.
    
      [0] Closes: https://github.com/libbpf/libbpf/issues/311
    
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20211111053624.190580-6-andrii@kernel.org

 src/libbpf.c   | 70 +++++++++++++++++++++++++++++++++++++----------
 src/libbpf.h   | 86 +++++++++++++++++++++++++++++++++++++++++++++++++---------
 src/libbpf.map |  4 +++
 3 files changed, 132 insertions(+), 28 deletions(-)
```

**Comment by yanivagman** [comment]
Further investigation revealed that the new API of perf_buffer__new() is being called instead of the old API.
That means that instead of calling:
```
struct perf_buffer *perf_buffer__new_deprecated(int map_fd, size_t page_cnt,
                                               const struct perf_buffer_opts *opts)
```
This function is called:
```
struct perf_buffer *perf_buffer__new_v0_6_0(int map_fd, size_t page_cnt,
                                           perf_buffer_sample_fn sample_cb,
                                           perf_buffer_lost_fn lost_cb,
                                           void *ctx,
                                           const struct perf_buffer_opts *opts)
```

Then, the values of sample_cb, lost_cb, and ctx are incorrect, which cause the panic described above.

Looking at the way libbpf decides which version of the API to choose, it uses macros to decide about the correct version to use according to the given number of arguments to the function.

My current understanding of what is going on is that cgo doesn't understand these macros games, and uses the default API, which resolves to the new API that we don't use in libbpfgo. If that is correct and cgo doesn't know how to handle these APIs, we should either stick with the old libbpf version, or update libbpfgo to use the newest libbpf API when bumping libbpf's version.

**Comment by rafaeldtinoco** [comment]
Hum, that doesn't happen in my environment... curious. I'm in favor of changing libbpfgo for the new API to avoid issues.

**Comment by yanivagman** [comment]
> Hum, that doesn't happen in my environment... curious. I'm in favor of changing libbpfgo for the new API to avoid issues but, if we want faster stabilization we can make the call the outdated API function in a new libbpfgo release and then open an issue to move to the new API.

Indeed it is interesting why it happens on my environment and not in yours.
Just to be sure, did you use `make clean` so that libbpf.a is rebuilt?

**Comment by rafaeldtinoco** [comment]
Could you, please, try changes made at https://github.com/aquasecurity/libbpfgo/pull/123 (https://github.com/aquasecurity/libbpfgo/pull/123/commits/0443255c0d2af6d0184733786401d856407ef59f and https://github.com/aquasecurity/libbpfgo/pull/123/commits/d7b5d006151ac37837415320b0378f75323eb2fe) and see if it solves the issue ?

Thank you.

**Comment by yanivagman** [comment]
> Could you, please, try changes made at [aquasecurity/libbpfgo#123](https://github.com/aquasecurity/libbpfgo/pull/123) ([aquasecurity/libbpfgo@0443255](https://github.com/aquasecurity/libbpfgo/commit/0443255c0d2af6d0184733786401d856407ef59f) and [aquasecurity/libbpfgo@d7b5d00](https://github.com/aquasecurity/libbpfgo/commit/d7b5d006151ac37837415320b0378f75323eb2fe)) and see if it solves the issue ?
> 
> Thank you.

Works! Thanks @rafaeldtinoco
