### ISSUE TITLE
[BUG] failing tests after container enrichment feature

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1767]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):

After merging the container enrichment feature, the tests have become flaky and there was one of the tests pointing out race conditions.

This is the error I'm getting:

```
Loaded 1 signature(s): [TRC-3]
VM INFO: tracee is up
no containerId
fatal error: concurrent map read and map write

goroutine 28 [running]:
runtime.throw({0x160b0f2?, 0xc000d23f40?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000059ea8 sp=0xc000059e78 pc=0x957b91
runtime.mapaccess2_fast64(0xc000059fa0?, 0x15e0d88?, 0x100000010)
	/usr/local/go/src/runtime/map_fast64.go:62 +0x176 fp=0xc000059ec8 sp=0xc000059ea8 pc=0x9335d6
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func1()
	/tracee/pkg/ebpf/events_enrich.go:63 +0x3b1 fp=0xc000059fe0 sp=0xc000059ec8 pc=0x12863f1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x988561
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).enrichContainerEvents
	/tracee/pkg/ebpf/events_enrich.go:25 +0x1ea

goroutine 1 [chan receive]:
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Run(0xc0000001e0, {0x1d1f1d8?, 0xc000535f40})
	/tracee/pkg/ebpf/tracee.go:1128 +0x245
main.main.func1(0xc0005758c0)
	/tracee/cmd/tracee-ebpf/main.go:293 +0x1905
github.com/urfave/cli/v2.(*App).RunContext(0xc000512ea0, {0x1d1f210?, 0xc000040088}, {0xc00003c090, 0x9, 0x9})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x953

goroutine 53 [semacquire]:
sync.runtime_Semacquire(0x20746f6e20736920?)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x204243445f34545f?)
	/usr/local/go/src/sync/waitgroup.go:136 +0x52
github.com/aquasecurity/tracee/pkg/ebpf.MergeErrors.func2()
	/tracee/pkg/ebpf/events_pipeline.go:348 +0x26
created by github.com/aquasecurity/tracee/pkg/ebpf.MergeErrors
	/tracee/pkg/ebpf/events_pipeline.go:347 +0x17f

goroutine 55 [select]:
net/http.(*persistConn).roundTrip(0xc000d60a20, 0xc000d17100)
	/usr/local/go/src/net/http/transport.go:2620 +0x974
net/http.(*Transport).roundTrip(0xc00050c000, 0xc000112c00)
	/usr/local/go/src/net/http/transport.go:594 +0x7c9
net/http.(*Transport).RoundTrip(0xc0003d9290?, 0x1d15180?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc000112c00, {0x1d15180, 0xc00050c000}, {0x15ba9c0?, 0xc00066ad01?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00060bd10, 0xc000112c00, {0x8?, 0xffff00ffffffffff?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00060bd10, 0xc000112c00)
	/usr/local/go/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
github.com/docker/docker/client.(*Client).doRequest(0xc000554400, {0x1d1f248, 0xc0005f2cc0}, 0xc000112b00)
	/root/go/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:125 +0x288
github.com/docker/docker/client.(*Client).sendRequest(0x10?, {0x1d1f248, 0xc0005f2cc0}, {0x15d517b, 0x3}, {0xc0000952c0?, 0x7?}, 0x0?, {0x0, 0x0}, ...)
	/root/go/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:113 +0xd3
github.com/docker/docker/client.(*Client).get(...)
	/root/go/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/request.go:37
github.com/docker/docker/client.(*Client).ContainerInspect(0xa?, {0x1d1f248, 0xc0005f2cc0}, {0xc00029d4bd, 0x40})
	/root/go/pkg/mod/github.com/docker/docker@v20.10.13+incompatible/client/container_inspect.go:18 +0x10e
github.com/aquasecurity/tracee/pkg/containers/runtime.(*dockerEnricher).Get(0xc0005b0110, {0xc00029d4bd?, 0x40?}, {0x1d1f248, 0xc0005f2cc0})
	/tracee/pkg/containers/runtime/docker.go:31 +0xbd
github.com/aquasecurity/tracee/pkg/containers.(*runtimeInfoService).Get(0xc00065d520?, {0xc00029d4bd, 0x40}, 0x1?, {0x1d1f248, 0xc0005f2cc0})
	/tracee/pkg/containers/service.go:41 +0xde
github.com/aquasecurity/tracee/pkg/containers.(*Containers).EnrichCgroupInfo(0xc000088900, 0x100000028)
	/tracee/pkg/containers/containers.go:254 +0x288
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func1.1()
	/tracee/pkg/ebpf/events_enrich.go:67 +0x6a
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func1
	/tracee/pkg/ebpf/events_enrich.go:66 +0x47a

goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0x7fb93f8c0130, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0003be800?, 0xc000d66000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0003be800, {0xc000d66000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003be800, {0xc000d66000?, 0x0?, 0x4?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000105f8, {0xc000d66000?, 0xc0000105f0?, 0x1?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc000d60a20, {0xc000d66000?, 0x96a740?, 0xc00065fec8?})
	/usr/local/go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc0005f3020)
	/usr/local/go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc0005f3020, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc000d60a20)
	/usr/local/go/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1750 +0x173e

goroutine 42 [select]:
net/http.(*persistConn).writeLoop(0xc000d60a20)
	/usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x1791
```

## Steps to reproduce

Run the weekly tests on an affected tree.

## Context

Relevant information about my setup:

* Linux version: CentOS Stream 9
* Linux kernel version: 5.14.0-86.el9.x86_64
* Tracee version (or commit id of your tree): ea912b58
* LLVM version: version 13.0.1 (Red Hat 13.0.1-1.el9)
* Golang version: go1.18.2 linux/amd64

**Comment by rafaeldtinoco** [comment]
I'm also getting:

```
Loaded 1 signature(s): [TRC-3]
VM INFO: tracee is up
no containerId
Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/containers/09ed8af38928763c82b38c7ae9fa5cacdaae7961f65bc39496e419353ef64ca3/json": context deadline exceeded
```
when running in a fully virtualized environment (much slower)

or just:

```
Loaded 1 signature(s): [TRC-3]
VM INFO: tracee is up
no containerId
```
in an accelerated (KVM) environment.

**Comment by rafaeldtinoco** [comment]
I believe:

```
fatal error: concurrent map read and map write
```

Relates to `queues` map (needs confirmation). But, if we protect it by a mutex, then we will block the pipeline (exactly what we are trying to avoid):

<img width="780" alt="image" src="https://user-images.githubusercontent.com/7395852/168939108-fdea1bc8-f17f-4f9f-bfcf-5ae878aaf4b4.png">

And, considering the 10 sec timeout, the cache might be up to 10MB * 10seconds (100MB). Flushing 100MBs can hold the pipeline for a long time.

I think we should test and discuss this a bit more and then merge it back again.
