### ISSUE TITLE
[BUG] Container enrichment feature causes lockup in the pipeline

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#1873]
## Bug description

In order to test container enrichment impact in performance, and with a bit of my `chaos engineering hat`, I have created a **simple testcase** close to what we used to test **initial performance numbers** (when we found out ratio from producer->consumer).

The idea is simple:

- Before: we used to run `while true; do ps -ef; done`
- After: add containers running **same test case** for some time.

By starting the new test, I'm able to get up to 14MB/s with JSON output, a good indication that I'm doing what I wanted. After a very quick time, the pipeline stops ending events out and seems locked/stuck.

The process stack trace will be attached so it can be analyzed. I have also compiled tracee-ebpf with `-race` but it showed no apparent root cause for the lockup.

By manually removing `enrichContainerEvents` from the pipeline I'm able to do what I was supposed to: run `stress.sh`, stop it, see pipeline draining down, run `stress.sh` test again, see new events coming, pipeline being drained, etc.

## Steps to reproduce

Run tracee with:

```
$ sudo ./dist/tracee-ebpf -trace container -o format:json -o option:parse-arguments -o option:detect-syscall
```

Create a docker container with:

```Dockerfile
FROM ubuntu:jammy

ARG uid=1000
ARG gid=1000

# install needed environment

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y sudo coreutils findutils && \
    apt-get install -y bash git curl rsync && \
    apt-get install -y llvm clang golang make gcc && \
    apt-get install -y linux-headers-generic && \
    apt-get install -y libelf-dev && \
    apt-get install -y zlib1g-dev

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y man bash-completion && \
    apt-get install -y net-tools iproute2 wget vim && \
    apt-get install -y stress

# allow TRACEE* and LIBBPFGO* environment variables through sudo

RUN echo "Defaults env_keep += \"LANG LC_* HOME EDITOR PAGER GIT_PAGER MAN_PAGER\"" > /etc/sudoers && \
    echo "Defaults env_keep += \"LIBBPFGO* TRACEE*\"" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "rafaeldtinoco ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    chmod 0440 /etc/sudoers

RUN export uid=$uid gid=$gid && \
    mkdir -p /home/rafaeldtinoco && \
    echo "rafaeldtinoco:x:${uid}:${gid}:rafaeldtinoco,,,:/home/rafaeldtinoco:/bin/bash" >> /etc/passwd && \
    echo "rafaeldtinoco:x:${gid}:" >> /etc/group && \
    echo "rafaeldtinoco::99999:0:99999:7:::" >> /etc/shadow && \
    chown ${uid}:${gid} -R /home/rafaeldtinoco && \
    echo "export PS1=\"\u@\h[\w]$ \"" > /home/rafaeldtinoco/.bashrc && \
    echo "alias ls=\"ls --color\"" >> /home/rafaeldtinoco/.bashrc && \
    echo ". /usr/share/bash-completion/bash_completion" >> /home/rafaeldtinoco/.bashrc && \
    echo "set -o vi" >> /home/rafaeldtinoco/.bashrc && \
    ln -s /home/rafaeldtinoco/.bashrc /home/rafaeldtinoco/.profile

COPY ./loop.sh /
COPY ./entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

USER rafaeldtinoco
ENV HOME /home/rafaeldtinoco
WORKDIR /home/rafaeldtinoco
```

Where `entrypoint.sh` is:

```bash
#!/bin/bash

timeout --preserve-status --foreground --signal=9 3s /loop.sh
```

and `loop.sh` is:

```bash
#!/bin/bash

while true; do ps -ef; done
```

and `stress.sh` is:

```bash
#!/bin/bash

while true; do

docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu &
docker run --rm -t mine:ubuntu

done
```

**Comment by rafaeldtinoco** [comment]
The stack trace for this situation is bellow. I have "filtered out" some unimportant (to check the race) info. I would say we are stuck at:

```
goroutine 82 [semacquire]:
    sync.runtime_SemacquireMutex()                                      /usr/lib/go-1.18/src/runtime/sema.go:71
    sync.(*RWMutex).Lock()                                              /usr/lib/go-1.18/src/sync/rwmutex.go:144
    tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func2()             ./pkg/ebpf/events_enrich.go:153
created by tracee/pkg/ebpf.(*Tracee).enrichContainerEvents              ./pkg/ebpf/events_enrich.go:88
```

But this was a very quick look trying to help @NDStrahilevitz if he has time to work on this tomorrow. If not I can continue.

```
SIGABRT: abort
PC= sigcode=0

goroutine 0 [idle]:
runtime.futex() /usr/lib/go-1.18/src/runtime/sys_linux_amd64.s:552
runtime.futexsleep() /usr/lib/go-1.18/src/runtime/os_linux.go:66
runtime.notesleep() usr/lib/go-1.18/src/runtime/lock_futex.go:159
runtime.mPark(...) /usr/lib/go-1.18/src/runtime/proc.go:1449
runtime.stopm() /usr/lib/go-1.18/src/runtime/proc.go:2228
runtime.findrunnable() /usr/lib/go-1.18/src/runtime/proc.go:2804
runtime.schedule() /usr/lib/go-1.18/src/runtime/proc.go:3187
runtime.park_m(?) /usr/lib/go-1.18/src/runtime/proc.go:3336
runtime.mcall() /usr/lib/go-1.18/src/runtime/asm_amd64.s:425

// main

goroutine 1 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.(*Tracee).Run(...)                                  ./pkg/ebpf/tracee.go:1098
    main.main.func1()                                                   ./cmd/tracee-ebpf/main.go:294
    github.com/urfave/cli/v2.(*App).RunContext(...)                     github.com/urfave/cli/v2@v2.3.0/app.go:322 3
    github.com/urfave/cli/v2.(*App).Run(...)                            github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main() ./cmd/tracee-ebpf/main.go:369

goroutine 66 [select, 1 minutes]:
    main.main.func1.3()                                                 ./cmd/tracee-ebpf/main.go:265
created by main.main.func1                                              ./cmd/tracee-ebpf/main.go:264

goroutine 67 [select]:
    main.main.func1.4()                                                 ./cmd/tracee-ebpf/main.go:275
created by main.main.func1                                              ./cmd/tracee-ebpf/main.go:272

goroutine 48 [syscall, 1 minutes]:
    os/signal.signal_recv()                                             /usr/lib/go-1.18/src/runtime/sigqueue.go:151
    os/signal.loop()                                                    /usr/lib/go-1.18/src/os/signal/signal_unix.go:23
created by os/signal.Notify.func1.1                                     /usr/lib/go-1.18/src/os/signal/signal.go:151

// libbpfgo

goroutine 68 [chan send, locked to thread]:
    libbpfgo.perfCallback()                                             .../libbpf_cb.go:14
    libbpfgo._Cfunc_perf_buffer__poll()                                 ./gotypes.go:920
    libbpfgo.(*PerfBuffer).poll.func1()                                 .../libbpfgo.go:1140
    libbpfgo.(*PerfBuffer).poll()                                       .../libbpfgo.go:1140
created by libbpfgo.(*PerfBuffer).Start                                 .../libbpfgo.go:1086

goroutine 69 [syscall]:
    libbpfgo._Cfunc_perf_buffer__poll()                                 ./gotypes.go:920
    libbpfgo.(*PerfBuffer).poll.func1()                                 .../libbpfgo.go:1140
    libbpfgo.(*PerfBuffer).poll()                                       .../libbpfgo.go:1140
created by libbpfgo.(*PerfBuffer).Start                                 .../libbpfgo.go:1086

goroutine 70 [syscall]:
    libbpfgo._Cfunc_perf_buffer__poll()                                 ./gotypes.go:920
    libbpfgo.(*PerfBuffer).poll.func1()                                 .../libbpfgo.go:1140
    libbpfgo.(*PerfBuffer).poll()                                       .../libbpfgo.go:1140
created by libbpfgo.(*PerfBuffer).Start                                 .../libbpfgo.go:1086

# mutexes/semaphores

goroutine 90 [semacquire, 1 minutes]:
    sync.runtime_Semacquire()                                           /usr/lib/go-1.18/src/runtime/sema.go:56
    sync.(*WaitGroup).Wait()                                            /usr/lib/go-1.18/src/sync/waitgroup.go:136
    tracee/pkg/ebpf.MergeErrors.func2()                                 ./pkg/ebpf/events_pipeline.go:352
created by tracee/pkg/ebpf.MergeErrors                                  ./pkg/ebpf/events_pipeline.go:351

goroutine 82 [semacquire]:
    sync.runtime_SemacquireMutex()                                      /usr/lib/go-1.18/src/runtime/sema.go:71
    sync.(*RWMutex).Lock()                                              /usr/lib/go-1.18/src/sync/rwmutex.go:144
    tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func2()             ./pkg/ebpf/events_enrich.go:153
created by tracee/pkg/ebpf.(*Tracee).enrichContainerEvents              ./pkg/ebpf/events_enrich.go:88

# pipeline

goroutine 71 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.(*Tracee).processLostEvents()                       ./pkg/ebpf/events_processor.go:22
created by tracee/pkg/ebpf.(*Tracee).Run                                ./pkg/ebpf/tracee.go:1093

goroutine 72 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.(*Tracee).WaitForPipeline()                         ./pkg/ebpf/events_pipeline.go:321
    tracee/pkg/ebpf.(*Tracee).handleEvents()                            ./pkg/ebpf/events_pipeline.go:62
created by tracee/pkg/ebpf.(*Tracee).Run                                ./pkg/ebpf/tracee.go:1094

goroutine 73 [select, 1 minutes]:
    tracee/pkg/ebpf.(*Tracee).processFileWrites()                       ./pkg/ebpf/write_capture.go:26
created by tracee/pkg/ebpf.(*Tracee).Run                                ./pkg/ebpf/tracee.go:1095

goroutine 74 [select, 1 minutes]:
    tracee/pkg/ebpf.(*Tracee).processNetEvents()                        ./pkg/ebpf/net_events.go:208
created by tracee/pkg/ebpf.(*Tracee).Run                                ./pkg/ebpf/tracee.go:1096

goroutine 32 [select]:
    tracee/pkg/ebpf.(*Tracee).processEvents.func1()                     ./pkg/ebpf/events_pipeline.go:248
created by tracee/pkg/ebpf.(*Tracee).processEvents                      ./pkg/ebpf/events_pipeline.go:228

goroutine 33 [chan send]:
    tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func1()             ./pkg/ebpf/events_enrich.go:81
created by tracee/pkg/ebpf.(*Tracee).enrichContainerEvents              ./pkg/ebpf/events_enrich.go:29

goroutine 83 [select]:
    tracee/pkg/ebpf.(*Tracee).deriveEvents.func1()                      ./pkg/ebpf/events_derived.go:73
created by tracee/pkg/ebpf.(*Tracee).deriveEvents                       ./pkg/ebpf/events_derived.go:68

goroutine 84 [chan receive]:
    tracee/pkg/ebpf.(*Tracee).sinkEvents.func1()                        ./pkg/ebpf/events_pipeline.go:263
created by tracee/pkg/ebpf.(*Tracee).sinkEvents                         ./pkg/ebpf/events_pipeline.go:261

# pipeline merge errors

goroutine 85 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.MergeErrors.func1()                                 ./pkg/ebpf/events_pipeline.go:339
created by tracee/pkg/ebpf.MergeErrors                                  ./pkg/ebpf/events_pipeline.go:346

goroutine 86 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.MergeErrors.func1()                                 ./pkg/ebpf/events_pipeline.go:339
created by tracee/pkg/ebpf.MergeErrors                                  ./pkg/ebpf/events_pipeline.go:346

goroutine 87 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.MergeErrors.func1()                                 ./pkg/ebpf/events_pipeline.go:339
created by tracee/pkg/ebpf.MergeErrors                                  ./pkg/ebpf/events_pipeline.go:346

goroutine 88 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.MergeErrors.func1()                                 ./pkg/ebpf/events_pipeline.go:339
created by tracee/pkg/ebpf.MergeErrors                                  ./pkg/ebpf/events_pipeline.go:346

goroutine 89 [chan receive, 1 minutes]:
    tracee/pkg/ebpf.MergeErrors.func1()                                 ./pkg/ebpf/events_pipeline.go:339
created by tracee/pkg/ebpf.MergeErrors                                  ./pkg/ebpf/events_pipeline.go:346

# sockets communication (grpc, sockets, similar)

goroutine 45 [select, 1 minutes]:
    google.golang.org/grpc.(*ccBalancerWrapper).watcher()               google.golang.org/grpc@v1.47.0/balancer_conn_wrappers.go:112
created by google.golang.org/grpc.newCCBalancerWrapper                  google.golang.org/grpc@v1.47.0/balancer_conn_wrappers.go:73

goroutine 31 [select]:
    tracee/pkg/ebpf.(*Tracee).decodeEvents.func1()                      ./pkg/ebpf/events_pipeline.go:215
created by tracee/pkg/ebpf.(*Tracee).decodeEvents                       ./pkg/ebpf/events_pipeline.go:133

goroutine 25 [select, 1 minutes]:
    google.golang.org/grpc.(*ccBalancerWrapper).watcher()               google.golang.org/grpc@v1.47.0/balancer_conn_wrappers.go:112
created by google.golang.org/grpc.newCCBalancerWrapper                  google.golang.org/grpc@v1.47.0/balancer_conn_wrappers.go:73

goroutine 222 [select]:
    net/http.(*persistConn).writeLoop()                                 /usr/lib/go-1.18/src/net/http/transport.go:2392
created by net/http.(*Transport).dialConn                               /usr/lib/go-1.18/src/net/http/transport.go:1751

goroutine 30 [select, 1 minutes]:
    google.golang.org/grpc/internal/transport.(*controlBuffer).get()    golang.org/grpc@v1.47.0/internal/transport/controlbuf.go:408
    google.golang.org/grpc/internal/transport.(*loopyWriter).run()      google.golang.org/grpc@v1.47.0/internal/transport/controlbuf.go:535
    google.golang.org/grpc/internal/transport.newHTTP2Client.func3()    google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:415
created by google.golang.org/grpc/internal/transport.newHTTP2Client     google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:413

goroutine 13 [select, 1 minutes]:
    google.golang.org/grpc/internal/transport.(*controlBuffer).get()    golang.org/grpc@v1.47.0/internal/transport/controlbuf.go:408
    google.golang.org/grpc/internal/transport.(*loopyWriter).run()      google.golang.org/grpc@v1.47.0/internal/transport/controlbuf.go:535
    google.golang.org/grpc/internal/transport.newHTTP2Client.func3()    google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:415
created by google.golang.org/grpc/internal/transport.newHTTP2Client     google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:413

goroutine 12 [IO wait, 1 minutes]:
    internal/poll.runtime_pollWait(...)                                 runtime/netpoll.go:302
    internal/poll.(*pollDesc).wait(...)                                 internal/poll/fd_poll_runtime.go:83
    internal/poll.(*pollDesc).waitRead(...)                             /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
    internal/poll.(*FD).Read()                                          /usr/lib/go-1.18/src/internal/poll/fd_unix.go:167
    net.(*netFD).Read(...)                                              /usr/lib/go-1.18/src/net/fd_posix.go:55
    net.(*conn).Read(...)                                               /usr/lib/go-1.18/src/net/net.go:183
    bufio.(*Reader).Read(...)                                           /usr/lib/go-1.18/src/bufio/bufio.go:236
    io.ReadAtLeast(...)                                                 /usr/lib/go-1.18/src/io/io.go:331
    io.ReadFull(...)                                                    /usr/lib/go-1.18/src/io/io.go:350
    golang.org/x/net/http2.readFrameHeader(...)                         golang.org/x/net@.../http2/frame.go:237
    golang.org/x/net/http2.(*Framer).ReadFrame()                        golang.org/x/net@.../http2/frame.go:498
    google.golang.org/grpc/internal/transport.(*http2Client).reader()   google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:1498
created by google.golang.org/grpc/internal/transport.newHTTP2Client     google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:365

goroutine 29 [IO wait, 1 minutes]:
    internal/poll.runtime_pollWait()                                    /usr/lib/go-1.18/src/runtime/netpoll.go:302
    internal/poll.(*pollDesc).wait()                                    /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:83
    internal/poll.(*pollDesc).waitRead(...)                             /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
    internal/poll.(*FD).Read(, {, , 0})                                 /usr/lib/go-1.18/src/internal/poll/fd_unix.go:167
    net.(*netFD).Read()                                                 /usr/lib/go-1.18/src/net/fd_posix.go:55
    net.(*conn).Read()                                                  /usr/lib/go-1.18/src/net/net.go:183
    bufio.(*Reader).Read()                                              /usr/lib/go-1.18/src/bufio/bufio.go:236
    io.ReadAtLeast()                                                    /usr/lib/go-1.18/src/io/io.go:331
    io.ReadFull(...)                                                    /usr/lib/go-1.18/src/io/io.go:350
    golang.org/x/net/http2.readFrameHeader()                            golang.org/x/net@.../http2/frame.go:237
    golang.org/x/net/http2.(*Framer).ReadFrame()                        golang.org/x/net@.../http2/frame.go:498
    google.golang.org/grpc/internal/transport.(*http2Client).reader()   google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:1498
created by google.golang.org/grpc/internal/transport.newHTTP2Client     google.golang.org/grpc@v1.47.0/internal/transport/http2_client.go:365

goroutine 54 [IO wait]:
    internal/poll.runtime_pollWait()                                    /usr/lib/go-1.18/src/runtime/netpoll.go:302
    internal/poll.(*pollDesc).wait()                                    /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:83
    internal/poll.(*pollDesc).waitRead(...)                             /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
    internal/poll.(*FD).Read()                                          /usr/lib/go-1.18/src/internal/poll/fd_unix.go:167 a
    net.(*netFD).Read()                                                 /usr/lib/go-1.18/src/net/fd_posix.go:55
    net.(*conn).Read()                                                  /usr/lib/go-1.18/src/net/net.go:183
    net/http.(*persistConn).Read()                                      /usr/lib/go-1.18/src/net/http/transport.go:1929
    bufio.(*Reader).fill()                                              /usr/lib/go-1.18/src/bufio/bufio.go:106
    bufio.(*Reader).Peek()                                              /usr/lib/go-1.18/src/bufio/bufio.go:144
    net/http.(*persistConn).readLoop()                                  /usr/lib/go-1.18/src/net/http/transport.go:2093
created by net/http.(*Transport).dialConn                               /usr/lib/go-1.18/src/net/http/transport.go:1750

goroutine 55 [select]:
    net/http.(*persistConn).writeLoop()                                 /usr/lib/go-1.18/src/net/http/transport.go:2392
created by net/http.(*Transport).dialConn                               /usr/lib/go-1.18/src/net/http/transport.go:1751

goroutine 221 [IO wait]:
    internal/poll.runtime_pollWait()                                    /usr/lib/go-1.18/src/runtime/netpoll.go:302
    internal/poll.(*pollDesc).wait()                                    /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:83
    internal/poll.(*pollDesc).waitRead(...)                             /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
    internal/poll.(*FD).Read()                                          /usr/lib/go-1.18/src/internal/poll/fd_unix.go:167 a
    net.(*netFD).Read()                                                 /usr/lib/go-1.18/src/net/fd_posix.go:55
    net.(*conn).Read()                                                  /usr/lib/go-1.18/src/net/net.go:183
    net/http.(*persistConn).Read()                                      /usr/lib/go-1.18/src/net/http/transport.go:1929
    bufio.(*Reader).fill()                                              /usr/lib/go-1.18/src/bufio/bufio.go:106
    bufio.(*Reader).Peek()                                              /usr/lib/go-1.18/src/bufio/bufio.go:144
    net/http.(*persistConn).readLoop()                                  /usr/lib/go-1.18/src/net/http/transport.go:2093
created by net/http.(*Transport).dialConn                               /usr/lib/go-1.18/src/net/http/transport.go:1750
```
