### ISSUE TITLE
[BUG] Fatal error on segmentation fault

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2188]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

I just compiled and ran the current main branch and it crashes upon running.
The error I get is the following:
```
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
libbpf: failed to get EHDR from /proc/config.gz
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffff05f pc=0x7f5a0f2f9de1]

runtime stack:
runtime.throw({0x16c83e3?, 0xb834d1a?})
	/usr/lib/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall]:
runtime.cgocall(0x13cba50, 0xc0006dd300)
	/usr/lib/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0006dd2d8 sp=0xc0006dd2a0 pc=0x94e59c
github.com/aquasecurity/libbpfgo._Cfunc_bpf_object__load(0x46d4fa0)
	_cgo_gotypes.go:989 +0x4c fp=0xc0006dd300 sp=0xc0006dd2d8 pc=0xabdb4c
github.com/aquasecurity/libbpfgo.(*Module).BPFLoadObject.func1(0xc0000ccb00?)
	/home/alonz/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.0-libbpf-1.0.0.0.20220919160735-14c6bc9b8a05/libbpfgo.go:522 +0x46 fp=0xc0006dd338 sp=0xc0006dd300 pc=0xac0566
github.com/aquasecurity/libbpfgo.(*Module).BPFLoadObject(0xc001177540?)
	/home/alonz/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.0-libbpf-1.0.0.0.20220919160735-14c6bc9b8a05/libbpfgo.go:522 +0x19 fp=0xc0006dd380 sp=0xc0006dd338 pc=0xac0499
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).initBPF(0xc000188000)
	/home/alonz/go/src/tracee/pkg/ebpf/tracee.go:1067 +0x1e5 fp=0xc0006dd460 sp=0xc0006dd380 pc=0x134ee25
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Init(0xc000188000)
	/home/alonz/go/src/tracee/pkg/ebpf/tracee.go:372 +0x369 fp=0xc0006dd5a8 sp=0xc0006dd460 pc=0x134a709
main.main.func1(0xc0005ec9c0)
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:261 +0x1645 fp=0xc0006ddcc8 sp=0xc0006dd5a8 pc=0x13c69a5
github.com/urfave/cli/v2.(*App).RunContext(0xc00055e4e0, {0x1ebad60?, 0xc0000400f0}, {0xc00003c220, 0x1, 0x1})
	/home/alonz/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x953 fp=0xc0006dde58 sp=0xc0006ddcc8 pc=0x13ae453
github.com/urfave/cli/v2.(*App).Run(...)
	/home/alonz/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:357 +0xd7d fp=0xc0006ddf80 sp=0xc0006dde58 pc=0x13c80dd
runtime.main()
	/usr/lib/go/src/runtime/proc.go:250 +0x212 fp=0xc0006ddfe0 sp=0xc0006ddf80 pc=0x985e72
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0006ddfe8 sp=0xc0006ddfe0 pc=0x9b42a1

goroutine 9 [syscall]:
os/signal.signal_recv()
	/usr/lib/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/lib/go/src/os/signal/signal.go:151 +0x2a

goroutine 19 [select]:
main.main.func1.2()
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:232 +0x71
created by main.main.func1
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:231 +0x151e

goroutine 20 [select]:
main.main.func1.3()
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:242 +0x16a
created by main.main.func1
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:239 +0x15be
```
Clarification - I updated to the current `libbpfgo` and ran `make clean` before compilation.

## Context

Relevant information about my setup:

* Linux version: Manjaro
* Linux kernel version: 5.10.126-1-MANJARO
* Tracee version (or commit id of your tree): 4f2d828fe52e21a4bcac3de6e1a66c258ef8f14c

**Comment by AlonZivony** [comment]
@rafaeldtinoco @grantseltzer I hope you can help me with it

**Comment by yanivagman** [comment]
We already seen this bug: https://github.com/aquasecurity/tracee/pull/2146#issuecomment-1239498911
Libbpfgo was bumped again yesterday, were it should have been already fixed (but apparently it wasn't)

**Comment by josedonizetti** [comment]
@AlonZivony can you try:

```
make clean
git submodule update
go ​clean -modcache
make
# test
```

Both @NDStrahilevitz and I saw the same error, and it was due to mod cache.

**Comment by AlonZivony** [comment]
> @AlonZivony can you try:
> 
> ```
> make clean
> git submodule update
> go ​clean -modcache
> // clean your GOCACHE  directory (go env | grep GOCACHE)
> make
> # test
> ```
> 
> Both @NDStrahilevitz and I saw the same error, and it was due to mod cache.

No, got the same error :(

**Comment by AlonZivony** [comment]
OK, thanks to @josedonizetti the problem was solved.
In my case, the fix was to delete to `GOCACHE` directory (run `go env | grep -i CACHE` to find it or just `echo $GOCACHE`).
So I guess the following commands should solve the problem to anyone having it too:
```
rm -rf $GOCACHE
make clean
make
```
Make sure to update your submodules too.
