### ISSUE TITLE
[BUG] symbols_loaded event with partial args filters cause segfault

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#2285]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

Bug with using nil pointer to arguments filters in the initialization of the `symbols_loaded` event.

This is how I'm executing tracee (cmdline):
`./dist/tracee-ebpf -t e=symbols_loaded -t symbols_loaded.symbols=fopen`

This is the error I'm getting:
```
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS

End of events stream
Stats: {EventCount:0 EventsFiltered:0 NetEvCount:0 ErrorCount:0 LostEvCount:0 LostWrCount:0 LostNtCount:0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13ac5d3]

goroutine 1 [running]:
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).initDerivationTable(0xc000714d80)
	/home/alonz/go/src/tracee/pkg/ebpf/tracee.go:607 +0xc33
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Init(0xc000714d80)
	/home/alonz/go/src/tracee/pkg/ebpf/tracee.go:418 +0x33c
main.main.func1(0xc000688d40)
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:266 +0x1505
github.com/urfave/cli/v2.(*App).RunContext(0xc000003860, {0x1fcfec0?, 0xc000120000}, {0xc000132000, 0x5, 0x5})
	/home/alonz/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
	/home/alonz/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/alonz/go/src/tracee/cmd/tracee-ebpf/main.go:365 +0xd5a
```

**Comment by yanivagman** [comment]
Fixed by #2284
