### ISSUE TITLE
[BUG] symbols_loaded segmentation fault when failed to open file

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2396]
## Prerequisites

- [x] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):
`sudo ./tracee-ebpf -t e=symbols_loaded -t symbols_loaded.symbols=fopen`

This is the error I'm getting:
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xa4d5d4]

goroutine 58 [running]:
debug/elf.(*File).Close(0x8cd365?)
	/usr/local/go/src/debug/elf/file.go:223 +0x14
panic({0x148d9e0, 0x25b6590})
	/usr/local/go/src/runtime/panic.go:838 +0x207
debug/elf.(*File).getSymbols(0xc001583890?, 0xd?)
	/usr/local/go/src/debug/elf/file.go:477 +0x18
debug/elf.(*File).DynamicSymbols(0xc00004a020?)
	/usr/local/go/src/debug/elf/file.go:1270 +0x27
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.loadSharedObjectDynamicSymbols({0xc001884570?, 0x2?})
	/home/eitani/projects/tracee/pkg/utils/sharedobjs/host_symbols_loader.go:112 +0x14d
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.(*HostSymbolsLoader).loadSOSymbols(0xc00000e720, {{0x68, 0x3d, 0x172bc5307a7a4556}, {0xc001884570, 0x29}, 0xf0000001})
	/home/eitani/projects/tracee/pkg/utils/sharedobjs/host_symbols_loader.go:67 +0x82
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.(*HostSymbolsLoader).GetExportedSymbols(0x1e84620?, {{0x68, 0x3d, 0x172bc5307a7a4556}, {0xc001884570, 0x29}, 0xf0000001})
	/home/eitani/projects/tracee/pkg/utils/sharedobjs/host_symbols_loader.go:45 +0x69
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.(*ContainersSymbolsLoader).GetExportedSymbols(0xc00000e738, {{0x68, 0x3d, 0x172bc5307a7a4556}, {0xc001884570, 0x29}, 0xf0000001})
	/home/eitani/projects/tracee/pkg/utils/sharedobjs/container_symbols_loader.go:37 +0xad
github.com/aquasecurity/tracee/pkg/events/derive.(*symbolsLoadedEventGenerator).deriveArgs(_, {0x172bc5307ab3b4b6, 0x6ba51adfa, 0x2, 0x749, 0x1, 0x79e, 0x743, 0x749, 0x79e, ...})
	/home/eitani/projects/tracee/pkg/events/derive/symbols_loaded.go:80 +0x137
github.com/aquasecurity/tracee/pkg/events/derive.deriveSingleEvent.func1({0x172bc5307ab3b4b6, 0x6ba51adfa, 0x2, 0x749, 0x1, 0x79e, 0x743, 0x749, 0x79e, 0x743, ...})
	/home/eitani/projects/tracee/pkg/events/derive/derive.go:59 +0x78
github.com/aquasecurity/tracee/pkg/events/derive.DeriveEvent({0x172bc5307ab3b4b6, 0x6ba51adfa, 0x2, 0x749, 0x1, 0x79e, 0x743, 0x749, 0x79e, 0x743, ...}, ...)
	/home/eitani/projects/tracee/pkg/events/derive/derive.go:28 +0x1a2
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).deriveEvents.func1()
	/home/eitani/projects/tracee/pkg/ebpf/events_pipeline.go:290 +0x238
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).deriveEvents
	/home/eitani/projects/tracee/pkg/ebpf/events_pipeline.go:280 +0x10a

```
## Steps to reproduce

Steps to reproduce the issue:

1. run tracee
2. run elf that can't be opened by tracee

## Context

This commit is the cause of the bug:
https://github.com/aquasecurity/tracee/commit/84fd91ecd952da41a81424ace6b34a79cd43ff74#diff-2216524976be0db30ff6c5cf29001174d71b94d01dddc09990502e0312da7e35L109
The error checked was removed.

**Comment by rafaeldtinoco** [comment]
Fixed by https://github.com/aquasecurity/tracee/pull/2450
