### ISSUE TITLE
[BUG] crash due to nil pointer dereference in loadSharedObjectDynamicSymbols in v0.9.3

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2442]
## Prerequisites

- [x] This affects latest released version.
- [ ] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

```
Hostname: gke-enforcer-ov
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xaa9674]

goroutine 31 [running]:
debug/elf.(*File).Close(0x9154c5?)
        /usr/lib/go-1.18/src/debug/elf/file.go:223 +0x14
panic({0x154c340, 0x26e1590})
        /usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
debug/elf.(*File).getSymbols(0xc006274fa8?, 0x12?)
        /usr/lib/go-1.18/src/debug/elf/file.go:477 +0x18
debug/elf.(*File).DynamicSymbols(0xc00052cf00?)
        /usr/lib/go-1.18/src/debug/elf/file.go:1270 +0x27
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.loadSharedObjectDynamicSymbols({0xc004a63a80?, 0x2?})
        /home/rafaeldtinoco/tracee/pkg/utils/sharedobjs/host_symbols_loader.go:112 +0x14d
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.(*HostSymbolsLoader).loadSOSymbols(0xc001ba6540, {{0x333478, 0x31e, 0x172d8f4ef11f2615}, {0xc004a63a80, 0x3a}, 0xf0000c0c})
        /home/rafaeldtinoco/tracee/pkg/utils/sharedobjs/host_symbols_loader.go:67 +0x82
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.(*HostSymbolsLoader).GetExportedSymbols(0x1f5a080?, {{0x333478, 0x31e, 0x172d8f4ef11f2615}, {0xc004a63a80, 0x3a}, 0xf0000c0c})
        /home/rafaeldtinoco/tracee/pkg/utils/sharedobjs/host_symbols_loader.go:45 +0x69
github.com/aquasecurity/tracee/pkg/utils/sharedobjs.(*ContainersSymbolsLoader).GetExportedSymbols(0xc001ba6558, {{0x333478, 0x31e, 0x172d8f4ef11f2615}, {0xc004a63a80, 0x3a}, 0xf0000c0c})
        /home/rafaeldtinoco/tracee/pkg/utils/sharedobjs/container_symbols_loader.go:37 +0xad
github.com/aquasecurity/tracee/pkg/events/derive.(*symbolsLoadedEventGenerator).deriveArgs(_, {0x172e5ad95f0bde2f, 0xcbbb891e1672, 0x3, 0x1, 0x100014e6c, 0x1, 0x8505c, 0x85162, 0x85162, ...})
        /home/rafaeldtinoco/tracee/pkg/events/derive/symbols_loaded.go:80 +0x137
github.com/aquasecurity/tracee/pkg/events/derive.deriveSingleEvent.func1({0x172e5ad95f0bde2f, 0xcbbb891e1672, 0x3, 0x1, 0x100014e6c, 0x1, 0x8505c, 0x85162, 0x85162, 0x8505c, ...})
        /home/rafaeldtinoco/tracee/pkg/events/derive/derive.go:59 +0x78
github.com/aquasecurity/tracee/pkg/events/derive.DeriveEvent({0x172e5ad95f0bde2f, 0xcbbb891e1672, 0x3, 0x1, 0x100014e6c, 0x1, 0x8505c, 0x85162, 0x85162, 0x8505c, ...}, ...)
        /home/rafaeldtinoco/tracee/pkg/events/derive/derive.go:28 +0x1a2
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).deriveEvents.func1()
        /home/rafaeldtinoco/tracee/pkg/ebpf/events_pipeline.go:290 +0x238
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).deriveEvents
        /home/rafaeldtinoco/tracee/pkg/ebpf/events_pipeline.go:280 +0x10a
```

## Steps to reproduce

```
./run_tracee_ebpf.sh | ./tracee/dist/tracee-rules --pprof --metrics --input-tracee=file:stdin --input-tracee format:gob
``` 

## Context

Relevant information about my setup:

* Linux version: Ubuntu Focal
* Linux kernel version: 5.4.0-1081-gke
* Tracee version (or commit id of your tree): v0.9.3
* LLVM version: 13
* Golang version: 1.18

**Comment by rafaeldtinoco** [comment]
@AlonZivony FYI
