### ISSUE TITLE
[BUG] Sorting Events nil pointer dereference

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2449]
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):

```
~/run_tracee/run_tracee_ebpf.sh | ./tracee/dist/tracee-rules --pprof --metrics --input-tracee=file:stdin --input-tracee format:gob
```

This is the error I'm getting:

```
*** Detection ***
Time: 2022-12-07T14:19:31Z
Signature ID: TRC-180
Signature: Privileges change detect
Data: map[Process lineage:[]]
Command: runc:[2:INIT]
Hostname: sample-webhook-

*** Detection ***
Time: 2022-12-07T14:19:31Z
Signature ID: TRC-180
Signature: Privileges change detect
Data: map[Process lineage:[]]
Command: runc:[2:INIT]
Hostname: sample-webhook-
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1371e26]

goroutine 54 [running]:
github.com/aquasecurity/tracee/pkg/events/sorting.(*EventsChronologicalSorter).getUpdatedMostDelayedLastCPUEventTimestamp(0xc006e127d0)
        /home/rafaeldtinoco/tracee/pkg/events/sorting/sorting.go:269 +0x126
github.com/aquasecurity/tracee/pkg/events/sorting.(*EventsChronologicalSorter).updateSavedTimestamps(0xc006e127d0)
        /home/rafaeldtinoco/tracee/pkg/events/sorting/sorting.go:217 +0x25
github.com/aquasecurity/tracee/pkg/events/sorting.(*EventsChronologicalSorter).Start(0xc006e127d0, 0xc0096b6000, 0xc0096b60c0, {0x1ffe4f8, 0xc00070d900}, 0x0?)
        /home/rafaeldtinoco/tracee/pkg/events/sorting/sorting.go:170 +0x1d2
created by github.com/aquasecurity/tracee/pkg/events/sorting.(*EventsChronologicalSorter).StartPipeline
        /home/rafaeldtinoco/tracee/pkg/events/sorting/sorting.go:148 +0x10d
tracee@gke-enforcer-overhea-workload-node-po-1a611035-f4lx[~]$ 
```

**Comment by rafaeldtinoco** [comment]
@AlonZivony FYI
