### ISSUE TITLE
tracee can't load signature produced binary artifact tar.gz

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#2778]
## Description

```
fatal error: runtime: no plugin module data

goroutine 1 [running]:
runtime.throw({0x183394e?, 0x46ec1b?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0008a6ea0 sp=0xc0008a6e70 pc=0x43e07d
plugin.lastmoduleinit()
        /usr/local/go/src/runtime/plugin.go:20 +0x8ce fp=0xc0008a6f88 sp=0xc0008a6ea0 pc=0x46ea6e
plugin.open({0xc000170340, 0x33})
        /usr/local/go/src/plugin/plugin_dlopen.go:77 +0x3ef fp=0xc0008a71f8 sp=0xc0008a6f88 pc=0xbbaa0f
plugin.Open(...)
        /usr/local/go/src/plugin/plugin.go:32
github.com/aquasecurity/tracee/pkg/rules/signature.findGoSigs.func1.1({0xc000170340, 0x33}, {0x216aba8, 0xc00021eb00}, {0x0?, 0x0?})
        /tracee/pkg/rules/signature/signature.go:78 +0x1c9 fp=0xc0008a72d8 sp=0xc0008a71f8 pc=0x132c2e9
path/filepath.walkDir({0xc000170340, 0x33}, {0x216aba8, 0xc00021eb00}, 0xc0008a74d0)
        /usr/local/go/src/path/filepath/path.go:398 +0x5c fp=0xc0008a7398 sp=0xc0008a72d8 pc=0x581f5c
path/filepath.walkDir({0xc00016a750, 0x28}, {0x216ac18, 0xc0005f6570}, 0xc0008a74d0)
        /usr/local/go/src/path/filepath/path.go:420 +0x2aa fp=0xc0008a7458 sp=0xc0008a7398 pc=0x5821aa
path/filepath.WalkDir({0xc00016a750, 0x28}, 0xc0008a74d0)
        /usr/local/go/src/path/filepath/path.go:484 +0xb0 fp=0xc0008a74b8 sp=0xc0008a7458 pc=0x582690
github.com/aquasecurity/tracee/pkg/rules/signature.findGoSigs.func1()
        /tracee/pkg/rules/signature/signature.go:67 +0x45 fp=0xc0008a74f0 sp=0xc0008a74b8 pc=0x132c105
github.com/aquasecurity/tracee/pkg/capabilities.(*Capabilities).Requested(0xc00007cc80, 0x0?, {0xc0008a75c8?, 0xc00016a750?, 0x28?})
        /tracee/pkg/capabilities/capabilities.go:211 +0xf9 fp=0xc0008a75a0 sp=0xc0008a74f0 pc=0xda4859
github.com/aquasecurity/tracee/pkg/rules/signature.findGoSigs({0xc00016a750?, 0x28?})
        /tracee/pkg/rules/signature/signature.go:65 +0xdb fp=0xc0008a7618 sp=0xc0008a75a0 pc=0x132c07b
github.com/aquasecurity/tracee/pkg/rules/signature.Find({0x17f1276, 0x4}, 0x9?, {0x0?, 0x163a6e0?}, {0x33038b8, 0x0, 0x8aebfb?}, 0xe0?)
        /tracee/pkg/rules/signature/signature.go:32 +0x150 fp=0xc0008a7880 sp=0xc0008a7618 pc=0x132b950
main.main.func1(0xc00026b200?)
        /tracee/cmd/tracee/main.go:69 +0x189 fp=0xc0008a7c88 sp=0xc0008a7880 pc=0x132d9a9
github.com/urfave/cli/v2.(*App).RunContext(0xc0007031e0, {0x2169590?, 0xc000044058}, {0xc000040220, 0x1, 0x1})
        /home/tracee/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c fp=0xc0008a7e18 sp=0xc0008a7c88 pc=0xf272bc
github.com/urfave/cli/v2.(*App).Run(...)
        /home/tracee/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /tracee/cmd/tracee/main.go:211 +0x1036 fp=0xc0008a7f80 sp=0xc0008a7e18 pc=0x132ed96
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0008a7fe0 sp=0xc0008a7f80 pc=0x440bf2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0008a7fe8 sp=0xc0008a7fe0 pc=0x473bc
```

## Output of `tracee -v`:

```
(paste your output here)
```

## Output of `uname -a`:

```
(paste your output here)
```

**Comment by rafaeldtinoco** [comment]
Like we've spoken today in the sync, this is actually a "feature" and not a "bug" (I've linked an old issue describing that the binaries in .tar.gz were compiled statically because or else we would have to create binaries for multiple glibc versions and/or distro versions).

So there is a decision (related to this issue) to be made. IMHO we should distribute in distro package files with the already existing building infrastructure for that (instead of .tar.gz files). Whoever wants to have binaries can use the "tracee-make" container image to build their own binaries (in their appropriate distro versions).

**Comment by yanivagman** [comment]
We can keep tar.gz artifact static, but for the very least we should exit gracefully instead of crashing
