### ISSUE TITLE
Panic when passing non existent policy file

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3053]
## Description

```
sudo ./dist/tracee --policy ./bsadas
Error: stat /home/ubuntu/tracee/bsadas: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x200 pc=0x199c731]

goroutine 1 [running]:
github.com/aquasecurity/tracee/pkg/policy.(*Policies).Map(...)
        /home/ubuntu/tracee/pkg/policy/policies.go:174
github.com/aquasecurity/tracee/pkg/ebpf.Config.Validate({0x0, 0x0, 0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
        /home/ubuntu/tracee/pkg/ebpf/tracee.go:112 +0x31
github.com/aquasecurity/tracee/pkg/ebpf.New({0x0, 0x0, 0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}, ...})
        /home/ubuntu/tracee/pkg/ebpf/tracee.go:292 +0x58
github.com/aquasecurity/tracee/pkg/cmd.Runner.Run({{0x0, 0x0, 0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...}, ...)
        /home/ubuntu/tracee/pkg/cmd/tracee.go:25 +0xdb
github.com/aquasecurity/tracee/cmd/tracee/cmd.glob..func2(0x3ae00a0?, {0x20612a8?, 0x2?, 0x2?})
        /home/ubuntu/tracee/cmd/tracee/cmd/root.go:41 +0x1bb
github.com/spf13/cobra.(*Command).execute(0x3ae00a0, {0xc00011c070, 0x2, 0x2})
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x3ae00a0)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/aquasecurity/tracee/cmd/tracee/cmd.Execute()
        /home/ubuntu/tracee/cmd/tracee/cmd/root.go:325 +0x7e
main.main()
        /home/ubuntu/tracee/cmd/tracee/main.go:8 +0x17
```

## Output of `tracee -v`:

```
Tracee version: "v0.14.0-3-g9e2c4214"
```

## Output of `uname -a`:

```
Linux ip-172-31-75-171 5.15.0-1031-aws #35-Ubuntu SMP Fri Feb 10 02:07:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by itaysk** [comment]
@NDStrahilevitz why did you close this? sounds reasonable

**Comment by NDStrahilevitz** [comment]
@itaysk I reproduced this is in a PR branch and not main, when I saw it doesn't reproduce in main I closed this and reported it to be fixed in the PR (which it then was). So the issue isn't actually relevant.
