### ISSUE TITLE
tracee is very slow when starting/stopping in kernels >= v6.1

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3150]
## Description

![image](https://github.com/aquasecurity/tracee/assets/7395852/aaa88729-06e9-4b4e-8243-758a316cff31)

```
$ sudo ./dist/tracee -f set=default
^CTIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
{"level":"error","ts":1685152201.7839,"msg":"Tracee encountered an error","error":"ebpf.FindingToEvent: error converting finding to event: "}
^C
```

A simple `ctrl+c` in a v6.3.1 kernel, when starting trace, takes up to ~1 min and the stack trace shows its on eBPF detaching logic (probe attaching and detaching became very slow in recent kernels, for a known fact already).

> I even thought there was a dead lock somewhere, but eventually tracee would exit cleanly after the following stack trace:

```
goroutine 0 [idle]:
runtime.epollwait() /usr/local/go/src/runtime/sys_linux_amd64.s:706 +0x20 fp=0x7fff032c1b98 sp=0x7fff032c1b90 pc=0xc6abc0
runtime.netpoll(0x13d21db3551?) /usr/local/go/src/runtime/netpoll_epoll.go:126 +0xdc fp=0x7fff032c21f8 sp=0x7fff032c1b98 pc=0xc2ebbc
runtime.findRunnable() /usr/local/go/src/runtime/proc.go:2837 +0x6a5 fp=0x7fff032c22e8 sp=0x7fff032c21f8 pc=0xc3af85
runtime.schedule() /usr/local/go/src/runtime/proc.go:3214 +0xbe fp=0x7fff032c2320 sp=0x7fff032c22e8 pc=0xc3c0fe
runtime.park_m(0xc0000071e0?) /usr/local/go/src/runtime/proc.go:3363 +0x14d fp=0x7fff032c2350 sp=0x7fff032c2320 pc=0xc3c62d
runtime.mcall() /usr/local/go/src/runtime/asm_amd64.s:448 +0x43 fp=0x7fff032c2360 sp=0x7fff032c2350 pc=0xc66843

goroutine 1 [syscall]:
runtime.cgocall(0x1c2c840, 0xc0002c2f68) /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc0002c2f40 sp=0xc0002c2f08 pc=0xbfab7c
github.com/aquasecurity/libbpfgo._Cfunc_bpf_link__destroy(0x7f3124001400) _cgo_gotypes.go:671 +0x4c fp=0xc0002c2f68 sp=0xc0002c2f40 pc=0x131b42c
github.com/aquasecurity/libbpfgo.(*BPFLink).Destroy.func1(0xc0002c3018?) /home/ubuntu/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.8-libbpf-1.2.0.0.20230509162948-80f41e18e690/libbpfgo.go:196 +0x46 fp=0xc0002c2fa0 sp=0xc0002c2f68 pc=0x131e3a6
github.com/aquasecurity/libbpfgo.(*BPFLink).Destroy(0xc0025c7bf0) /home/ubuntu/go/pkg/mod/github.com/aquasecurity/libbpfgo@v0.4.8-libbpf-1.2.0.0.20230509162948-80f41e18e690/libbpfgo.go:196 +0x25 fp=0xc0002c2fc0 sp=0xc0002c2fa0 pc=0x131e2e5
github.com/aquasecurity/tracee/pkg/ebpf/probes.(*traceProbe).detach(0xc002766d50, {0xc0002c3098?, 0xc4742f?, 0xc002732000?}) /home/ubuntu/tracee-rafael/pkg/ebpf/probes/trace.go:82 +0x36 fp=0xc0002c3028 sp=0xc0002c2fc0 pc=0x13464d6
github.com/aquasecurity/tracee/pkg/ebpf/probes.(*probes).DetachAll(0xbfd5b9?) /home/ubuntu/tracee-rafael/pkg/ebpf/probes/probes.go:201 +0x92 fp=0xc0002c30b8 sp=0xc0002c3028 pc=0x13460d2
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Close(0xc000462280) /home/ubuntu/tracee-rafael/pkg/ebpf/tracee.go:1587 +0x3d fp=0xc0002c3120 sp=0xc0002c30b8 pc=0x195f29d
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Run(0xc000462280, {0x2b92448, 0xc0001ee500}) /home/ubuntu/tracee-rafael/pkg/ebpf/tracee.go:1580 +0x905 fp=0xc0002c3400 sp=0xc0002c3120 pc=0x195ed85
github.com/aquasecurity/tracee/pkg/cmd.Runner.Run({{0xc0004deb40, 0xc0001eecc0, 0xc0001eed00, 0xc00062e699, {0x0, 0x0}, 0x400, 0x400, 0x0, {0x0, ...}, ...}, ...}, ...) /home/ubuntu/tracee-rafael/pkg/cmd/tracee.go:80 +0x365 fp=0xc0002c3988 sp=0xc0002c3400 pc=0x19dab65
github.com/aquasecurity/tracee/cmd/tracee/cmd.glob..func2(0x373d6c0?, {0x206156a?, 0x0?, 0x0?}) /home/ubuntu/tracee-rafael/cmd/tracee/cmd/root.go:42 +0x258 fp=0xc0002c3d28 sp=0xc0002c3988 pc=0x1c29798
github.com/spf13/cobra.(*Command).execute(0x373d6c0, {0xc000040210, 0x0, 0x0}) /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847 fp=0xc0002c3e60 sp=0xc0002c3d28 pc=0x12b1e87
github.com/spf13/cobra.(*Command).ExecuteC(0x373d6c0) /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd fp=0xc0002c3f18 sp=0xc0002c3e60 pc=0x12b279d
github.com/spf13/cobra.(*Command).Execute(...) /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/aquasecurity/tracee/cmd/tracee/cmd.Execute() /home/ubuntu/tracee-rafael/cmd/tracee/cmd/root.go:326 +0x7e fp=0xc0002c3f70 sp=0xc0002c3f18 pc=0x1c2af5e
main.main() /home/ubuntu/tracee-rafael/cmd/tracee/main.go:8 +0x17 fp=0xc0002c3f80 sp=0xc0002c3f70 pc=0x1c2b197
runtime.main() /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0002c3fe0 sp=0xc0002c3f80 pc=0xc35a52
runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0002c3fe8 sp=0xc0002c3fe0 pc=0xc68a81

goroutine 8 [select]:
runtime.gopark(0xc000073c48?, 0x2?, 0x0?, 0x0?, 0xc000073c3c?) /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000073958 sp=0xc000073938 pc=0xc35e16
runtime.selectgo(0xc000073c48, 0xc000073c38, 0x0?, 0x0, 0x0?, 0x1) /usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc000073a98 sp=0xc000073958 pc=0xc460fc
github.com/aquasecurity/tracee/pkg/cmd/printer.startPrinter(0xc00062e6d0?, 0xc000098a20, 0xc0001162a0, {0x2b93b40, 0xc000487d70}) /home/ubuntu/tracee-rafael/pkg/cmd/printer/broadcast.go:97 +0x16b fp=0xc000073fa8 sp=0xc000073a98 pc=0x18a054b
github.com/aquasecurity/tracee/pkg/cmd/printer.(*Broadcast).Init.func1() /home/ubuntu/tracee-rafael/pkg/cmd/printer/broadcast.go:51 +0x36 fp=0xc000073fe0 sp=0xc000073fa8 pc=0x18a0096
runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0xc68a81
created by github.com/aquasecurity/tracee/pkg/cmd/printer.(*Broadcast).Init /home/ubuntu/tracee-rafael/pkg/cmd/printer/broadcast.go:51 +0x50e

goroutine 46 [runnable]:
runtime.selectgo(0xc0025fdf90?, 0xc0025fdf60?, 0x0?, 0x0?, 0x2?, 0x1?) /usr/local/go/src/runtime/select.go:122 +0x1516 fp=0xc0025fdf10 sp=0xc0025fdf08 pc=0xc46e56
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).processLostEvents(0xc000462280) /home/ubuntu/tracee-rafael/pkg/ebpf/events_processor.go:40 +0xe5 fp=0xc0025fdfc8 sp=0xc0025fdf10 pc=0x194e145
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Run.func3() /home/ubuntu/tracee-rafael/pkg/ebpf/tracee.go:1518 +0x26 fp=0xc0025fdfe0 sp=0xc0025fdfc8 pc=0x195f1c6
runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0025fdfe8 sp=0xc0025fdfe0 pc=0xc68a81
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).Run /home/ubuntu/tracee-rafael/pkg/ebpf/tracee.go:1518 +0x29c
```

All the other routines were internal to golang runtime.
## Output of `tracee version`:

This is pre v0.15.0 version (freeze date)

## Output of `uname -a`:

```
v6.3.1 (upstream tree)
```

**Comment by rafaeldtinoco** [comment]
I'm not sure if this is good or bad, but I was not able to reproduce this with any upstream kernel anymore. Not even using the linux upstream tree (checked v6.1, v6.3). All tests return in ~5 sec or so.

I'll go ahead and close this but will keep it in mind if I see this behavior again I'll re-open (maybe its reproducible in a specific environment only ?).
