### ISSUE TITLE
races when loading/unloading tracee signatures (ctrl+c during initialization).

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3151]
## Description

```
$ sudo ./dist/tracee -f e=security_file_open
^CTIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 26 [running]:
sync.(*WaitGroup).Wait(0xc000030fc0?)
        /usr/local/go/src/sync/waitgroup.go:141 +0x85
github.com/aquasecurity/tracee/pkg/signatures/engine.(*Engine).checkCompletion(0xc000030fc0)
        /home/ubuntu/tracee-rafael/pkg/signatures/engine/engine.go:137 +0x3f
github.com/aquasecurity/tracee/pkg/signatures/engine.(*Engine).consumeSources(0xc000030fc0, {0x2b92448, 0xc0001fc4c0})
        /home/ubuntu/tracee-rafael/pkg/signatures/engine/engine.go:215 +0x3ea
github.com/aquasecurity/tracee/pkg/signatures/engine.(*Engine).Start(0xc000030fc0, {0x2b92448, 0xc0001fc4c0})
        /home/ubuntu/tracee-rafael/pkg/signatures/engine/engine.go:112 +0x1e7
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).engineEvents
        /home/ubuntu/tracee-rafael/pkg/ebpf/signature_engine.go:39 +0x473
```

## Output of `tracee version`:

Pre v0.15 (freeze date)

## Output of `uname -a`:

```
v6.3.1
```

**Comment by geyslan** [comment]
@rafaeldtinoco is this still relevant? I still haven't been able to reproduce.

**Comment by rafaeldtinoco** [comment]
This wait group is the signatures engine wait group and it is used do synchronize loading/unloading the signatures. I believe the ctrl+c made both logic to run concurrently and cause the issue.

I have not seen any recent changes in that code path, so its relevant I suppose (although not "high priority", but, still...).

**Comment by rafaeldtinoco** [comment]
Setting API server label because this will be sorted out when we go the dynamic loading/unloading of signatures.

**Comment by geyslan** [comment]
I've also assigned @josedonizetti since it can be connected to https://github.com/aquasecurity/tracee/pull/3188 solving.

**Comment by josedonizetti** [comment]
Looking into it today!
