### ISSUE TITLE
tracee: panic during initialization

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#3185]
## Description

```
$ sudo ./dist/tracee --config ~/policies/config.yaml --policy ~/policies/network/ 
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x18506b8]

goroutine 28 [running]:
github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).enrichContainerEvents.func1()
        /home/rafaeldtinoco/work/ebpf/tracee-libbpfgo/pkg/ebpf/events_enrich.go:79 +0x128
created by github.com/aquasecurity/tracee/pkg/ebpf.(*Tracee).enrichContainerEvents
        /home/rafaeldtinoco/work/ebpf/tracee-libbpfgo/pkg/ebpf/events_enrich.go:73 +0x1f4
```

## Output of `tracee version`:

```
v0.14.2-56-g234b9d0d
```

## Output of `uname -a`:

```
Linux azure 6.3.2 #5 SMP Tue May 16 04:48:36 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by rafaeldtinoco** [comment]
Since we're passing a channel of pointers, it is likely that the *tracee.Event gets NULL in the pipeline in the moment of shutdown, or similar logic, I believe.

In the pipeline, the caching step checks if event is null before moving on in both 'in/out' channels. 

![image](https://github.com/aquasecurity/tracee/assets/7395852/afd87112-5875-44de-8bb6-ef012313c7fc)

I believe the same should happen in the `enrich` pipeline stage:

![image](https://github.com/aquasecurity/tracee/assets/7395852/7ef31396-fbae-4eb6-b467-e0044c0d2a82)
