### ISSUE TITLE
tracee-rules panic observed

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#777]
One fine day the sun shine was shining bright and there were no clouds in the sky. But alas a panic was observed in tracee-rules...

```
sudo ./dist/tracee-ebpf -o format:gob | ./dist/tracee-rules --rules-dir=<path/to/rules-dir> --input-tracee file:stdin --input-tracee format:gob

<snip>

^Cpanic: send on closed channel

goroutine 137 [running]:
github.com/aquasecurity/tracee/tracee-rules/engine.(*Engine).consumeSources(0xc0008b3030, 0xc0001323f0)
	/usr/vagrant/repos/tracee/tracee-rules/engine/engine.go:114 +0x2b9
created by github.com/aquasecurity/tracee/tracee-rules/engine.(*Engine).Start
	/usr/vagrant/repos/tracee/tracee-rules/engine/engine.go:70 +0x65
```

This was just a normal invocation of tracee-ebpf and tracee-rules from the master branch. Nothing out of the ordinary to set it up.

**Comment by simar7** [comment]
Another instance without `rules-dir`

```
sudo ./dist/tracee-ebpf -o format:gob | ./dist/tracee-rules  --input-tracee file:stdin --input-tracee format:gob
Loaded signature(s):  [TRC-1 TRC-2 TRC-3 TRC-4 TRC-5 TRC-6 TRC-7]
^Cpanic: send on closed channel

goroutine 44 [running]:
github.com/aquasecurity/tracee/tracee-rules/engine.(*Engine).consumeSources(0xc000174b60, 0xc00006a000)
	/usr/vagrant/repos/tracee/tracee-rules/engine/engine.go:114 +0x2b9
created by github.com/aquasecurity/tracee/tracee-rules/engine.(*Engine).Start
	/usr/vagrant/repos/tracee/tracee-rules/engine/engine.go:70 +0x65
```

**Comment by mtcherni95** [comment]
@simar7 I am having some troubles in reproducing it. Any suggestion or specific action you did in order to get the error?

**Comment by simar7** [comment]
> @simar7 I am having some troubles in reproducing it. Any suggestion or specific action you did in order to get the error?

There's a reproducible test case and discussion here https://github.com/aquasecurity/tracee/pull/785#discussion_r657541451
