### ISSUE TITLE
Error running as container on Ubuntu 20.04

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/tracee#84]
```
root@vagrant:~# uname -a
Linux vagrant 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@vagrant:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
root@vagrant:~# docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro aquasec/tracee:latest
sh: 1: modprobe: not found
chdir(/lib/modules/5.4.0-31-generic/build): No such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5333c6]

goroutine 1 [running]:
github.com/iovisor/gobpf/bcc.(*Module).Load(0x0, 0xc00008ab30, 0xe, 0x2, 0x0, 0x0, 0xe, 0x10100c0000eb9b0, 0x0)
        /home/itaysk/.asdf/installs/golang/1.13.6/packages/pkg/mod/github.com/iovisor/gobpf@v0.0.0-20200417061255-f0a208deaea5/bcc/module.go:202 +0x26
github.com/iovisor/gobpf/bcc.(*Module).LoadKprobe(...)
        /home/itaysk/.asdf/installs/golang/1.13.6/packages/pkg/mod/github.com/iovisor/gobpf@v0.0.0-20200417061255-f0a208deaea5/bcc/module.go:177
github.com/aquasecurity/tracee/tracee.(*Tracee).initBPF(0xc0000ba280, 0xc00012c000, 0xad01, 0x0, 0x61e3c1)
        /home/itaysk/dev/tracee/tracee/tracee.go:237 +0x579
github.com/aquasecurity/tracee/tracee.New(0xc000070800, 0x3f, 0x3f, 0x0, 0x61e3c1, 0x5, 0x40, 0xc0000b86c0, 0x0, 0x0)
        /home/itaysk/dev/tracee/tracee/tracee.go:193 +0x1cd
main.main.func1(0xc0000b8680, 0xc000080b00, 0xe)
        /home/itaysk/dev/tracee/main.go:33 +0x2fc
github.com/urfave/cli/v2.(*App).RunContext(0xc000066600, 0x666060, 0xc00008a020, 0xc0000721b0, 0x1, 0x1, 0x0, 0x0)
        /home/itaysk/.asdf/installs/golang/1.13.6/packages/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x6be
github.com/urfave/cli/v2.(*App).Run(...)
        /home/itaysk/.asdf/installs/golang/1.13.6/packages/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
        /home/itaysk/dev/tracee/main.go:84 +0x670
```

**Comment by itaysk** [comment]
The error indicates it fails to find the kernel headers at `/lib/modules/5.4.0-31-generic/build`. are they there? can you post the 2-level deep dir structure under `/lib/modules/`? 

Another thing that worries me is that my personal paths are shown in the stack trace. can you make sure you are using the latest image from dockerhub? (force pull it)
https://hub.docker.com/layers/aquasec/tracee/0.0.1/images/sha256-ff8f01a63a87531bd4f5ae02ec037a1720c3a12d93263b7bfc82a4acc76e3237?context=explore

**Comment by itaysk** [comment]
@lizrice is this still an issue for you?

**Comment by itaysk** [comment]
closing this for irrelevance (tracee has changed significantly enough)
